add_newline = false

format = """$directory$character"""

palette = "poimandres"

right_format = """$all"""

command_timeout = 2000

[character]
vicmd_symbol = "[N] >>>"
success_symbol = '[➜ :](bold #5de4c7)'
error_symbol = '[➜ :](bold #d0679d)'

[directory.substitutions]
'~/tests/starship-custom' = 'work-project'

[git_branch]
format = '[$symbol$branch (:$remote_branch)]($style)'
symbol = " "
style = "bold #d0679d"

[aws]
format = '[$symbol(profile: "$profile" )(\(region: $region\) )]($style)'
disabled = true
style = 'bold #89ddff'
symbol = " "

[docker_context]
disabled = true

[git_status]
style = "bold #5fb3a1"

[palettes.poimandres]
background = "#303340"
foreground = "#a6accd"

black = "#303340"
red = "#d0679d"
green = "#5de4c7"
yellow = "#fffac2"
blue = "#89ddff"
magenta = "#5fb3a1"
cyan = "#00ced1"
white = "#a6accd"

bright_black = "#767c9d"
bright_red = "#d0679d"
bright_green = "#5de4c7"
bright_yellow = "#fffac2"
bright_blue = "#add7ff"
bright_magenta = "#5fb3a1"
bright_cyan = "#00ced1"
bright_white = "#a6accd"
